-- PostgreSQL / Supabase schema for Praktikum Hukum Ohm
-- Updated for online hosting with database session and database cache.
-- Recommended .env:
-- SESSION_DRIVER=database
-- CACHE_STORE=database

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis VARCHAR(20) UNIQUE,
    name VARCHAR(150) NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('guru', 'siswa')),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- Laravel database sessions table
CREATE TABLE IF NOT EXISTS sessions (
    id VARCHAR(255) PRIMARY KEY,
    user_id BIGINT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS sessions_user_id_index
ON sessions (user_id);

CREATE INDEX IF NOT EXISTS sessions_last_activity_index
ON sessions (last_activity);

-- Laravel database cache table
CREATE TABLE IF NOT EXISTS cache (
    key VARCHAR(255) PRIMARY KEY,
    value TEXT NOT NULL,
    expiration INTEGER NOT NULL
);

-- Laravel database cache locks table
CREATE TABLE IF NOT EXISTS cache_locks (
    key VARCHAR(255) PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    expiration INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(1) UNIQUE NOT NULL,
    resistor_ohm INTEGER NOT NULL,
    title VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
    question_no INTEGER NOT NULL,
    voltage INTEGER NOT NULL,
    expected_current NUMERIC(10,3) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    UNIQUE(package_id, question_no)
);

CREATE TABLE IF NOT EXISTS practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    package_id BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
    attendance BOOLEAN DEFAULT TRUE,
    quiz_score INTEGER DEFAULT 0,
    practical_score INTEGER DEFAULT 0,
    manual_total_score INTEGER DEFAULT 0,
    total_score INTEGER DEFAULT 0,
    analysis_text TEXT,
    graph_json JSONB,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, package_id)
);

CREATE TABLE IF NOT EXISTS practice_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practice_session_id BIGINT NOT NULL REFERENCES practice_sessions(id) ON DELETE CASCADE,
    question_no INTEGER NOT NULL,
    voltage INTEGER NOT NULL,
    resistor_ohm INTEGER NOT NULL,
    student_answer NUMERIC(10,3) NOT NULL,
    expected_answer NUMERIC(10,3) NOT NULL,
    is_correct BOOLEAN DEFAULT FALSE,
    sensor_voltage NUMERIC(10,3),
    sensor_current NUMERIC(10,3),
    sensor_resistance NUMERIC(10,3),
    sensor_temp NUMERIC(10,3),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    UNIQUE(practice_session_id, question_no)
);

CREATE TABLE IF NOT EXISTS sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    practice_session_id BIGINT REFERENCES practice_sessions(id) ON DELETE CASCADE,
    source VARCHAR(30) DEFAULT 'simulation',
    voltage NUMERIC(10,3) NOT NULL,
    current NUMERIC(10,3) NOT NULL,
    resistance NUMERIC(10,3) NOT NULL,
    temperature NUMERIC(10,3) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

INSERT INTO packages (code, resistor_ohm, title)
VALUES
    ('A', 220, 'Paket A - Resistor 220 Ohm'),
    ('B', 330, 'Paket B - Resistor 330 Ohm'),
    ('C', 470, 'Paket C - Resistor 470 Ohm'),
    ('D', 550, 'Paket D - Resistor 550 Ohm')
ON CONFLICT (code) DO NOTHING;

-- Sample users.
-- Password hash for: guru1, siswa1, siswa2
INSERT INTO users (nis, name, username, password, role)
VALUES
    (NULL, 'Pak Guru', 'guru1', '$2y$12$M226bB4XD9mNO6lKg65m6ujDA9/cwLV5vuBiZ/kvdEiroGzrmTiUu', 'guru'),
    ('240001', 'Putera', 'siswa1', '$2y$12$vzgeBGbxYJcjmAI2RPFdyusrQuz0ooSUQIa4V/8/TSS11PWaI4uUO', 'siswa'),
    ('240002', 'Puteri', 'siswa2', '$2y$12$a29fdLwTaV8mvrSAQQPuf.ntgiwGt9JRtVTaT6IHR8mWJyeZRwGVS', 'siswa')
ON CONFLICT (username) DO NOTHING;

-- Sample questions for 4 packages x 4 items
INSERT INTO questions (package_id, question_no, voltage, expected_current)
SELECT
    p.id,
    q.question_no,
    q.voltage,
    q.expected_current
FROM packages p
JOIN (
    VALUES
        ('A', 1, 6, 0.027),
        ('A', 2, 8, 0.036),
        ('A', 3, 10, 0.045),
        ('A', 4, 12, 0.055),

        ('B', 1, 6, 0.018),
        ('B', 2, 8, 0.024),
        ('B', 3, 10, 0.030),
        ('B', 4, 12, 0.036),

        ('C', 1, 6, 0.013),
        ('C', 2, 8, 0.017),
        ('C', 3, 10, 0.021),
        ('C', 4, 12, 0.026),

        ('D', 1, 6, 0.011),
        ('D', 2, 8, 0.015),
        ('D', 3, 10, 0.018),
        ('D', 4, 12, 0.022)
) AS q(code, question_no, voltage, expected_current)
ON q.code = p.code
ON CONFLICT (package_id, question_no) DO NOTHING;

-- Sample finished session
INSERT INTO practice_sessions (
    user_id,
    package_id,
    attendance,
    quiz_score,
    practical_score,
    manual_total_score,
    total_score,
    analysis_text,
    graph_json,
    finished_at
)
SELECT
    u.id,
    p.id,
    TRUE,
    4,
    1,
    90,
    95,
    'Data menunjukkan arus meningkat saat tegangan naik, sedangkan nilai resistor tetap sesuai paket praktikum.',
    '{"points":[[6,220],[8,220],[10,220],[12,220]]}'::jsonb,
    NOW()
FROM users u
CROSS JOIN packages p
WHERE u.username = 'siswa1'
AND p.code = 'A'
ON CONFLICT (user_id, package_id) DO NOTHING;