-- PostgreSQL / Supabase schema for Praktikum Hukum Ohm
-- Run this in Supabase SQL Editor.

create table if not exists users (
  id bigint generated by default as identity primary key,
  nis varchar(20) unique,
  name varchar(150) not null,
  username varchar(100) unique not null,
  password varchar(255) not null,
  role varchar(20) not null check (role in ('guru', 'siswa')),
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create table if not exists packages (
  id bigint generated by default as identity primary key,
  code varchar(1) unique not null,
  resistor_ohm integer not null,
  title varchar(100) not null,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create table if not exists questions (
  id bigint generated by default as identity primary key,
  package_id bigint not null references packages(id) on delete cascade,
  question_no integer not null,
  voltage integer not null,
  expected_current numeric(10,3) not null,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  unique(package_id, question_no)
);

create table if not exists practice_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  package_id bigint not null references packages(id) on delete cascade,
  attendance boolean default true,
  quiz_score integer default 0,
  practical_score integer default 0,
  manual_total_score integer default 0,
  total_score integer default 0,
  analysis_text text,
  graph_json jsonb,
  finished_at timestamp without time zone,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  unique(user_id, package_id)
);

create table if not exists practice_answers (
  id bigint generated by default as identity primary key,
  practice_session_id bigint not null references practice_sessions(id) on delete cascade,
  question_no integer not null,
  voltage integer not null,
  resistor_ohm integer not null,
  student_answer numeric(10,3) not null,
  expected_answer numeric(10,3) not null,
  is_correct boolean default false,
  sensor_voltage numeric(10,3),
  sensor_current numeric(10,3),
  sensor_resistance numeric(10,3),
  sensor_temp numeric(10,3),
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  unique(practice_session_id, question_no)
);

create table if not exists sensor_readings (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  practice_session_id bigint references practice_sessions(id) on delete cascade,
  source varchar(30) default 'simulation',
  voltage numeric(10,3) not null,
  current numeric(10,3) not null,
  resistance numeric(10,3) not null,
  temperature numeric(10,3) not null,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

insert into packages (code, resistor_ohm, title)
values
  ('A', 220, 'Paket A - Resistor 220 Ohm'),
  ('B', 330, 'Paket B - Resistor 330 Ohm'),
  ('C', 470, 'Paket C - Resistor 470 Ohm'),
  ('D', 550, 'Paket D - Resistor 550 Ohm')
on conflict (code) do nothing;

-- Sample users. Password hash for: guru1, siswa1, siswa2
insert into users (nis, name, username, password, role)
values
  (null, 'Pak Guru', 'guru1', '$2y$12$M226bB4XD9mNO6lKg65m6ujDA9/cwLV5vuBiZ/kvdEiroGzrmTiUu', 'guru'),
  ('240001', 'Putera', 'siswa1', '$2y$12$vzgeBGbxYJcjmAI2RPFdyusrQuz0ooSUQIa4V/8/TSS11PWaI4uUO', 'siswa'),
  ('240002', 'Puteri', 'siswa2', '$2y$12$a29fdLwTaV8mvrSAQQPuf.ntgiwGt9JRtVTaT6IHR8mWJyeZRwGVS', 'siswa')
on conflict (username) do nothing;

-- Sample questions for 4 packages x 4 items
insert into questions (package_id, question_no, voltage, expected_current)
select p.id, q.question_no, q.voltage, q.expected_current
from packages p
join (
  values
    ('A', 1, 6, 0.027), ('A', 2, 8, 0.036), ('A', 3, 10, 0.045), ('A', 4, 12, 0.055),
    ('B', 1, 6, 0.018), ('B', 2, 8, 0.024), ('B', 3, 10, 0.030), ('B', 4, 12, 0.036),
    ('C', 1, 6, 0.013), ('C', 2, 8, 0.017), ('C', 3, 10, 0.021), ('C', 4, 12, 0.026),
    ('D', 1, 6, 0.011), ('D', 2, 8, 0.015), ('D', 3, 10, 0.018), ('D', 4, 12, 0.022)
) as q(code, question_no, voltage, expected_current)
  on q.code = p.code
on conflict (package_id, question_no) do nothing;

-- Sample finished session (optional)
insert into practice_sessions (user_id, package_id, attendance, quiz_score, practical_score, manual_total_score, total_score, analysis_text, graph_json, finished_at)
select u.id, p.id, true, 4, 1, 90, 95,
       'Data menunjukkan arus meningkat saat tegangan naik, sedangkan nilai resistor tetap sesuai paket praktikum.',
       '{"points":[[6,220],[8,220],[10,220],[12,220]]}'::jsonb,
       now()
from users u cross join packages p
where u.username = 'siswa1' and p.code = 'A'
on conflict (user_id, package_id) do nothing;
